name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey! Just wanted to let you know that I really appreciate you reporting bugs and issues :)"
        pr-message: "Try to describe your modifications/additions, that'd be awesome!"
